# Tmuxp session: Development
# Usage: tmuxp load dev

session_name: dev
start_directory: ~/Developer
windows:
  - window_name: editor
    panes:
      - nvim
  - window_name: shell
    panes:
      - # empty shell
  - window_name: servers
    layout: even-horizontal
    panes:
      - # server 1
      - # server 2
